# Generated by Django 5.2.8 on 2026-08-15 14:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMetadataPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='用途说明')),
                ('title_prompt', models.TextField(max_length=2000, verbose_name='标题提示词')),
                ('intro_prompt', models.TextField(max_length=2000, verbose_name='简介提示词')),
                ('tags_prompt', models.TextField(max_length=2000, verbose_name='标签提示词')),
                ('is_active', models.BooleanField(default=False, verbose_name='启用')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_ai_prompt_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_ai_prompt_templates_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '博客 AI 提示词',
                'verbose_name_plural': '博客 AI 提示词',
                'ordering': ['name', 'pk'],
            },
        ),
    ]
