# Generated by Django 5.1 on 2025-05-06 07:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('markdown_block', 1), ('embed_block', 2), ('table_block', 3), ('raw_html', 4), ('document_block', 5), ('image_block', 6), ('audio_block', 7), ('video_block', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'], 'label': '富文本'}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code', 'label': 'Markdown'}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': '从YouTube、Vimeo等插入内容', 'label': '嵌入媒体'}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': '表格'}), 4: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '适用于高级用户的HTML代码插入', 'label': '原始HTML'}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'icon': 'doc-full', 'label': '文档块'}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': '图片块'}), 7: ('wagtailmedia.blocks.AudioChooserBlock', (), {'icon': 'media', 'label': '音频块'}), 8: ('wagtailmedia.blocks.VideoChooserBlock', (), {'icon': 'media', 'label': '视频块'})}, default=[], null=True, verbose_name='内容'),
        ),
    ]
