# Generated by Django 5.1 on 2025-05-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': '博客页面', 'verbose_name_plural': '博客页面'},
        ),
    ]
