# Generated by Django 5.1 on 2025-05-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpagegalleryimage'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_remove_searchpromotion_query_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpage',
            index=models.Index(fields=['date'], name='blog_blogpa_date_978b39_idx'),
        ),
    ]
