# Generated by Django 5.1 on 2025-05-21 13:48

from django.db import migrations, models
import django.utils.timezone

def set_initial_dates(apps, schema_editor):
    BlogIndexPage = apps.get_model('blog', 'BlogIndexPage')
    for page in BlogIndexPage.objects.all():
        # 使用首次发布日期或当前日期作为初始值
        page.date = page.first_published_at.date() if page.first_published_at else django.utils.timezone.now().date()
        page.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpage_blog_blogpa_date_978b39_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='发布日期'),
        ),
        migrations.RunPython(set_initial_dates),
    ]