# Generated by Django 5.1 on 2025-05-22 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_add_date_to_blogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogimage'),
        ),
    ]
