# Generated by Django 5.1 on 2025-06-03 01:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogindexpage_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者列表'},
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'], 'icon': 'pilcrow', 'label': '段落'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': '图片'})}, verbose_name='个人简介'),
        ),
    ]
