# Generated by Django 5.2.8 on 2026-08-09 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_author_slugs(apps, schema_editor):
    """为已有作者建立稳定订阅地址，不改名也不修改文章关联。"""

    Author = apps.get_model("blog", "Author")
    used_slugs = set(Author.objects.exclude(slug__isnull=True).values_list("slug", flat=True))
    for author in Author.objects.filter(slug__isnull=True).order_by("pk").iterator():
        base_slug = slugify(author.name, allow_unicode=True) or "author"
        candidate = base_slug
        suffix = 2
        while candidate in used_slugs:
            candidate = f"{base_slug}-{suffix}"
            suffix += 1
        Author.objects.filter(pk=author.pk).update(slug=candidate)
        used_slugs.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_blogpage_body"),
        # Wagtail 7.4.2 的空合并迁移文件名可能随构建时间变化，直接依赖共同父节点以兼容各环境。
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailcore", "0097_merge_20250811_1740"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleEngagementSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("visitor_key", models.CharField(max_length=64)),
                ("session_id", models.UUIDField()),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("engaged", models.BooleanField(default=False)),
                ("max_scroll_percent", models.PositiveSmallIntegerField(default=0)),
                ("active_reading_seconds", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "文章阅读会话",
                "verbose_name_plural": "文章阅读会话",
            },
        ),
        migrations.CreateModel(
            name="FeedClientDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("global", "全站"),
                            ("tag", "标签"),
                            ("author", "作者"),
                        ],
                        max_length=10,
                    ),
                ),
                ("scope_id", models.PositiveIntegerField(default=0)),
                (
                    "feed_format",
                    models.CharField(
                        choices=[("rss", "RSS"), ("atom", "Atom")], max_length=10
                    ),
                ),
                ("client_key", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "订阅源客户端摘要",
                "verbose_name_plural": "订阅源客户端摘要",
            },
        ),
        migrations.CreateModel(
            name="FeedRequestDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("global", "全站"),
                            ("tag", "标签"),
                            ("author", "作者"),
                        ],
                        max_length=10,
                    ),
                ),
                ("scope_id", models.PositiveIntegerField(default=0)),
                ("scope_slug", models.CharField(blank=True, max_length=255)),
                ("scope_label", models.CharField(blank=True, max_length=255)),
                (
                    "feed_format",
                    models.CharField(
                        choices=[("rss", "RSS"), ("atom", "Atom")], max_length=10
                    ),
                ),
                ("response_200_count", models.PositiveBigIntegerField(default=0)),
                ("response_304_count", models.PositiveBigIntegerField(default=0)),
                ("estimated_client_count", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "订阅源请求统计",
                "verbose_name_plural": "订阅源请求统计",
            },
        ),
        migrations.CreateModel(
            name="PageTrafficSourceDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("source_category", models.CharField(max_length=20)),
                ("view_count", models.PositiveBigIntegerField(default=0)),
                ("unique_visitor_count", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "页面流量来源统计",
                "verbose_name_plural": "页面流量来源统计",
            },
        ),
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.RunPython(populate_author_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=255, unique=True
            ),
        ),
        migrations.AddField(
            model_name="pageview",
            name="active_reading_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pageview",
            name="engaged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pageview",
            name="first_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pageview",
            name="max_scroll_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pageview",
            name="scroll_50_reached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pageview",
            name="scroll_90_reached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pageview",
            name="referrer_host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pageview",
            name="source_category",
            field=models.CharField(default="direct", max_length=20),
        ),
        migrations.AddField(
            model_name="pageview",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pageview",
            name="visitor_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="pageviewcount",
            name="active_reading_seconds",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pageviewcount",
            name="engaged_visitor_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pageviewcount",
            name="scroll_50_visitor_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pageviewcount",
            name="scroll_90_visitor_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pageviewcount",
            name="unique_visitor_count_v2",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pageviewcount",
            name="v2_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pageviewcount",
            name="view_count_v2",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["date", "source_category"], name="blog_pagevi_date_9b7025_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pageview",
            constraint=models.UniqueConstraint(
                fields=("page", "date", "visitor_key"),
                name="blog_pageview_page_date_visitor_uniq",
            ),
        ),
        migrations.AddField(
            model_name="articleengagementsession",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagement_sessions",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="feedclientdaily",
            name="locale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.locale"
            ),
        ),
        migrations.AddField(
            model_name="feedclientdaily",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
            ),
        ),
        migrations.AddField(
            model_name="feedrequestdaily",
            name="locale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_request_counts",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="feedrequestdaily",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_request_counts",
                to="wagtailcore.site",
            ),
        ),
        migrations.AddField(
            model_name="pagetrafficsourcedaily",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traffic_sources",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddIndex(
            model_name="articleengagementsession",
            index=models.Index(
                fields=["date", "visitor_key"], name="blog_articl_date_119ffd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="articleengagementsession",
            constraint=models.UniqueConstraint(
                fields=("page", "session_id"), name="blog_engagement_page_session_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedclientdaily",
            constraint=models.UniqueConstraint(
                fields=(
                    "site",
                    "locale",
                    "date",
                    "scope_type",
                    "scope_id",
                    "feed_format",
                    "client_key",
                ),
                name="blog_feed_client_daily_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="feedrequestdaily",
            index=models.Index(
                fields=["date", "scope_type", "scope_id"],
                name="blog_feedre_date_41556a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedrequestdaily",
            constraint=models.UniqueConstraint(
                fields=(
                    "site",
                    "locale",
                    "date",
                    "scope_type",
                    "scope_id",
                    "feed_format",
                ),
                name="blog_feed_request_daily_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="pagetrafficsourcedaily",
            index=models.Index(
                fields=["date", "source_category"], name="blog_pagetr_date_04ccab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagetrafficsourcedaily",
            constraint=models.UniqueConstraint(
                fields=("page", "date", "source_category"),
                name="blog_traffic_source_daily_uniq",
            ),
        ),
    ]
