# Generated by Django 5.2.8 on 2026-08-17 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_alter_blogpage_body"),
        ("wagtailcore", "0098_merge_20260603_0945"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkdownImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("idempotency_key", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("success", "成功"),
                            ("partial_success", "部分成功"),
                            ("failed", "失败"),
                            ("cleanup_retry", "等待补偿清理"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "result_revision_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "mongo_content_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("test_run_id", models.UUIDField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "error_message",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "target_parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markdown_import_batches",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="markdown_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Markdown 导入批次",
                "verbose_name_plural": "Markdown 导入批次",
            },
        ),
        migrations.CreateModel(
            name="MarkdownImportArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("position", models.PositiveIntegerField()),
                ("media_type", models.CharField(max_length=16)),
                ("source_kind", models.CharField(max_length=24)),
                ("normalized_source", models.CharField(max_length=2048)),
                ("normalized_source_hash", models.CharField(max_length=64)),
                ("safe_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("succeeded", "成功"),
                            ("failed_missing", "失败并插入缺失标记"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "storage_alias",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "object_name",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "media_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "media_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "cleanup_status",
                    models.CharField(
                        choices=[
                            ("none", "无需清理"),
                            ("pending", "等待清理"),
                            ("retry", "清理重试"),
                            ("cleaned", "已清理"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "cleanup_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("cleanup_attempts", models.PositiveIntegerField(default=0)),
                ("cleanup_next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="blog.markdownimportbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Markdown 导入媒体",
                "verbose_name_plural": "Markdown 导入媒体",
            },
        ),
        migrations.AddIndex(
            model_name="markdownimportbatch",
            index=models.Index(
                fields=["status", "updated_at"], name="blog_md_batch_stat_upd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="markdownimportbatch",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="blog_md_import_user_key_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="markdownimportartifact",
            index=models.Index(
                fields=["status", "updated_at"], name="blog_md_art_stat_upd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="markdownimportartifact",
            index=models.Index(
                fields=["cleanup_status", "updated_at"],
                name="blog_md_art_clean_upd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="markdownimportartifact",
            constraint=models.UniqueConstraint(
                fields=("batch", "source_kind", "normalized_source_hash"),
                name="blog_md_artifact_source_uq",
            ),
        ),
    ]
