# Generated by Django 5.2.8 on 2026-08-19 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_markdown_import_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownImportToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_prefix', models.CharField(editable=False, max_length=24)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markdown_import_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Markdown 导入 Token',
                'verbose_name_plural': 'Markdown 导入 Token',
                'ordering': ('-created_at',),
            },
        ),
    ]
