# Generated by Django 5.2.8 on 2026-08-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_markdownimporttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownimporttoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='可选；填写 YYYY-MM-DD HH:MM，留空表示不过期。', null=True),
        ),
    ]
