# Generated by Django 5.2.8 on 2026-08-28 01:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_markdownimporttoken_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoCleanupIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('page_id', models.PositiveBigIntegerField()),
                ('pointer', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('formal', '正式正文'), ('revision', '历史快照')], max_length=16)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('retry', '待重试'), ('succeeded', '已完成'), ('skipped', '仍被引用'), ('dead', '终止')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at'], name='blog_mongo_cleanup_status_idx')],
            },
        ),
    ]
