# Generated by Django 5.2.8 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_mongo_cleanup_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mongocleanupintent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("retry", "待重试"),
                    ("processing", "处理中"),
                    ("succeeded", "已完成"),
                    ("skipped", "仍被引用"),
                    ("dead", "终止"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="mongocleanupintent",
            name="lease_reclaims",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mongocleanupintent",
            name="locked_by",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="mongocleanupintent",
            name="lock_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="mongocleanupintent",
            index=models.Index(
                fields=["status", "lock_expires_at"],
                name="blog_mongo_cleanup_lease_idx",
            ),
        ),
    ]
