# Generated by Django 5.2.8 on 2026-08-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_mongocleanupintent_leases'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPublicationState',
            fields=[
                ('page_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('draft_body_version_id', models.CharField(blank=True, max_length=128, null=True)),
                ('draft_body_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('draft_body_schema_version', models.PositiveIntegerField(blank=True, null=True)),
                ('published_body_version_id', models.CharField(blank=True, max_length=128, null=True)),
                ('published_body_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('published_body_schema_version', models.PositiveIntegerField(blank=True, null=True)),
                ('publication_generation', models.PositiveBigIntegerField(default=0)),
                ('approved_revision_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_revision_created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '博客发布状态',
                'verbose_name_plural': '博客发布状态',
                'indexes': [models.Index(fields=['approved_revision_id'], name='blog_pub_state_approved_idx')],
            },
        ),
    ]
