# Generated by Django 5.2.8 on 2026-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_blogpublicationstate_approved_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPublicationConsistencyCheckpoint',
            fields=[
                ('scope', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('cursor_page_id', models.PositiveBigIntegerField(default=0)),
                ('scan_upper_bound_page_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cycle', models.PositiveBigIntegerField(default=0)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=255)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_scanned', models.PositiveBigIntegerField(default=0)),
                ('last_counts', models.JSONField(default=dict)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog 对账检查点',
                'verbose_name_plural': 'Blog 对账检查点',
            },
        ),
    ]
