# Generated by Django 5.2.8 on 2026-08-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0033_blogpublicationconsistencycheckpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyBlogRegistrationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.PositiveBigIntegerField()),
                ("body_sha256", models.CharField(max_length=64)),
                ("body_schema_version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "处理中"),
                            ("succeeded", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="processing",
                        max_length=16,
                    ),
                ),
                (
                    "body_version_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "last_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("locked_by", models.CharField(blank=True, default="", max_length=128)),
                ("lock_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "lock_expires_at"],
                        name="blog_legacy_reg_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page_id", "body_sha256", "body_schema_version"),
                        name="blog_legacy_reg_page_hash_uq",
                    )
                ],
            },
        ),
    ]
