# Generated by Django 5.2

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0034_legacyblogregistrationaudit"),
    ]
    operations = [
        migrations.CreateModel(
            name="PageDeletionIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("intent_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("dedupe_key", models.CharField(max_length=160, unique=True)),
                ("page_id", models.PositiveBigIntegerField()),
                ("deletion_generation", models.PositiveBigIntegerField(default=1)),
                ("request_id", models.CharField(blank=True, default="", max_length=128)),
                ("actor_id", models.CharField(blank=True, default="", max_length=128)),
                ("status", models.CharField(choices=[("deleting", "删除中"), ("search_pending", "等待搜索墓碑"), ("mongo_pending", "等待 Mongo 清理"), ("partial_failed", "部分失败"), ("blocked_reference", "被共享引用阻断"), ("mysql_finalize_pending", "等待 MySQL 完成"), ("succeeded", "已完成"), ("dead", "终止")], default="deleting", max_length=32)),
                ("step", models.CharField(default="snapshot", max_length=32)),
                ("manifest", models.JSONField(default=dict)),
                ("deleted_counts", models.JSONField(default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("lease_reclaims", models.PositiveIntegerField(default=0)),
                ("lease_owner", models.CharField(blank=True, default="", max_length=128)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=64)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "available_at"], name="blog_page_delete_status_idx"),
                    models.Index(fields=["status", "lease_expires_at"], name="blog_page_delete_lease_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("page_id", "deletion_generation"), name="blog_page_delete_generation_uq"),
                ],
            },
        ),
    ]
