# Generated by Django 5.2.8 on 2026-08-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_pagedeletionintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedeletionintent',
            name='status',
            field=models.CharField(choices=[('deleting', '删除中'), ('processing', '处理中'), ('search_pending', '等待搜索墓碑'), ('mongo_pending', '等待 Mongo 清理'), ('partial_failed', '部分失败'), ('blocked_reference', '被共享引用阻断'), ('mysql_finalize_pending', '等待 MySQL 完成'), ('succeeded', '已完成'), ('dead', '终止')], default='deleting', max_length=32),
        ),
    ]
