# Generated by Django 5.2.8 on 2026-09-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_pagedeletionintent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdownimporttoken',
            name='token_encrypted',
            field=models.CharField(blank=True, editable=False, help_text='使用 AES-256-GCM 算法认证加密的明文密钥，支持管理员在后台免跳转复制。', max_length=255, null=True, verbose_name='AES-GCM加密密文'),
        ),
    ]
