# Generated by Django 5.1 on 2025-05-27 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_cta_homepage_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='发布日期'),
        ),
    ]
