# Generated by Django 5.2.8 on 2026-07-29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="LogClearAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idempotency_key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="操作时间")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="客户端 IP")),
                ("target", models.CharField(max_length=80, verbose_name="清理目标")),
                ("scope", models.CharField(max_length=20, verbose_name="清理范围")),
                ("files_before", models.PositiveIntegerField(default=0, verbose_name="文件数")),
                ("bytes_before", models.PositiveBigIntegerField(default=0, verbose_name="清理前字节数")),
                ("bytes_freed", models.PositiveBigIntegerField(default=0, verbose_name="释放字节数")),
                ("succeeded", models.BooleanField(default=True, verbose_name="是否成功")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="执行明细")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="log_clear_audits", to=settings.AUTH_USER_MODEL, verbose_name="操作人")),
            ],
            options={
                "verbose_name": "日志清理记录",
                "verbose_name_plural": "日志清理记录",
                "ordering": ("-created_at",),
                "permissions": (("view_logs", "可以查看系统日志"), ("manage_logs", "可以管理系统日志")),
            },
        )
    ]
