# Generated by Django 5.2.8 on 2026-07-30 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0003_audit_file_counts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logclearaudit',
            new_name='observabili_created_f9eca6_idx',
            old_name='observ_audit_created_state',
        ),
        migrations.RenameIndex(
            model_name='logclearaudit',
            new_name='observabili_target__114702_idx',
            old_name='observ_audit_target_kind',
        ),
        migrations.RenameIndex(
            model_name='logclearaudit',
            new_name='observabili_user_id_15309e_idx',
            old_name='observ_audit_user_created',
        ),
    ]
