# Generated by Django 5.2.8 on 2026-08-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observability", "0004_rename_observ_audit_created_state_observabili_created_f9eca6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(model_name="logclearaudit", name="index_sync_attempts", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="logclearaudit", name="index_sync_completed_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="logclearaudit", name="index_sync_deleted", field=models.PositiveBigIntegerField(default=0)),
        migrations.AddField(model_name="logclearaudit", name="index_sync_last_error", field=models.TextField(blank=True, default="")),
        migrations.AddField(
            model_name="logclearaudit",
            name="index_sync_state",
            field=models.CharField(db_index=True, default="not_required", max_length=20, verbose_name="Elasticsearch 同步状态"),
        ),
        migrations.AddField(model_name="logclearaudit", name="index_sync_task_id", field=models.CharField(blank=True, default="", max_length=128)),
        migrations.CreateModel(
            name="LogIndexSyncJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(default="pending", max_length=20)),
                ("selector", models.JSONField(default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("es_task_id", models.CharField(blank=True, default="", max_length=128)),
                ("deleted_documents", models.PositiveBigIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("dead_letter_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audit", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="index_sync_job", to="observability.logclearaudit")),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(fields=["state", "next_retry_at"], name="observ_idxsync_state_retry_idx"),
                    models.Index(fields=["created_at", "state"], name="observ_idxsync_created_idx"),
                ],
            },
        ),
    ]
