# Generated by Django 5.1 on 2025-05-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_formpage_formfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': '联系表单', 'verbose_name_plural': '联系表单'},
        ),
        migrations.AlterModelOptions(
            name='navigationsettings',
            options={'verbose_name': '社交链接'},
        ),
    ]
