# Generated by Django 5.1 on 2025-05-27 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_formpage_options_and_more'),
        ('blog', '0014_blogindexpage_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogpage'),
        ),
    ]
