# Generated by Django 5.1 on 2025-05-27 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_formpage_feature_image'),
        ('blog', '0014_blogindexpage_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogimage'),
        ),
    ]
