# Generated by Django 5.1 on 2025-05-27 13:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_formpage_feature_image'),
        ('blog', '0014_blogindexpage_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='confirmation_email_subject',
            field=models.CharField(blank=True, help_text='确认邮件主题', max_length=255),
        ),
        migrations.AddField(
            model_name='formpage',
            name='confirmation_email_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='确认邮件内容'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='send_confirmation_email',
            field=models.BooleanField(default=False, help_text='是否向提交者发送确认邮件'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='feature_image',
            field=models.ForeignKey(blank=True, help_text='表单页面的特色图片', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogimage'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='表单上方的介绍文本'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='表单提交成功后显示的感谢文本'),
        ),
    ]
