# Generated by Django 5.1 on 2025-05-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_formpage_confirmation_email_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': '联系表单页面', 'verbose_name_plural': '联系表单页面'},
        ),
        migrations.AlterField(
            model_name='formpage',
            name='send_confirmation_email',
            field=models.BooleanField(default=True, help_text='是否向提交者发送确认邮件'),
        ),
    ]
