# Generated by Django 5.1 on 2025-05-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_formpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': '联系表单页面（异步邮件）', 'verbose_name_plural': '联系表单页面（异步邮件）'},
        ),
        migrations.AddField(
            model_name='formpage',
            name='email_priority',
            field=models.CharField(choices=[('high', '高优先级'), ('normal', '普通优先级'), ('low', '低优先级')], default='normal', help_text='邮件发送的优先级，影响处理顺序', max_length=10),
        ),
        migrations.AddField(
            model_name='formpage',
            name='send_admin_notification',
            field=models.BooleanField(default=True, help_text='是否向管理员发送新提交通知邮件（异步发送）'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='send_confirmation_email',
            field=models.BooleanField(default=True, help_text='是否向提交者发送确认邮件（异步发送）'),
        ),
    ]
