# Generated by Django 5.2.8 on 2026-08-09 11:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_formpage_email_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='social_links',
            field=wagtail.fields.StreamField([('social_link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'label': '链接地址'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': '留空时，网站会根据链接域名显示平台名称。', 'label': '显示名称', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('url', 0), ('label', 1)]], {})}, help_text='按需添加并拖动排序。图标根据链接域名自动识别。', verbose_name='社交链接'),
        ),
    ]
