# Generated by Django 5.2.8 on 2026-08-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_social_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigationsettings",
            name="bilibili_url",
        ),
        migrations.RemoveField(
            model_name="navigationsettings",
            name="github_url",
        ),
        migrations.RemoveField(
            model_name="navigationsettings",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="navigationsettings",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="navigationsettings",
            name="wechat_url",
        ),
    ]
