# Generated by Django 5.2.8 on 2026-08-10 11:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSearchState',
            fields=[
                ('page_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('content_version', models.PositiveBigIntegerField(default=0)),
                ('desired_operation', models.CharField(choices=[('upsert', '写入'), ('tombstone', '墓碑')], default='upsert', max_length=16)),
                ('searchable', models.BooleanField(default=False)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('mongo_content_id', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '内容搜索状态',
                'verbose_name_plural': '内容搜索状态',
            },
        ),
        migrations.CreateModel(
            name='ContentSearchOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('page_id', models.PositiveBigIntegerField()),
                ('content_version', models.PositiveBigIntegerField()),
                ('operation', models.CharField(choices=[('upsert', '写入'), ('tombstone', '墓碑')], max_length=16)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('retry', '待重试'), ('succeeded', '已完成'), ('superseded', '已过期'), ('dead', '死信')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_by', models.CharField(blank=True, default='', max_length=128)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.TextField(blank=True, default='', max_length=2000)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '内容搜索事件',
                'verbose_name_plural': '内容搜索事件',
                'indexes': [models.Index(fields=['status', 'created_at'], name='srch_outbox_stat_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('page_id', 'content_version'), name='search_outbox_page_version_uq')],
            },
        ),
        migrations.CreateModel(
            name='ContentSearchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.SlugField(max_length=80, unique=True)),
                ('connection_name', models.SlugField(max_length=80)),
                ('index_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('serving', '服务中'), ('building', '构建中'), ('retired', '已退役')], default='serving', max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '内容搜索目标',
                'verbose_name_plural': '内容搜索目标',
                'indexes': [models.Index(fields=['enabled', 'role'], name='search_target_enabled_role_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentSearchDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('retry', '待重试'), ('succeeded', '已完成'), ('superseded', '已过期'), ('dead', '死信')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_by', models.CharField(blank=True, default='', max_length=128)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.TextField(blank=True, default='', max_length=2000)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='search.contentsearchoutbox')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='search.contentsearchtarget')),
            ],
            options={
                'verbose_name': '内容搜索投递',
                'verbose_name_plural': '内容搜索投递',
                'indexes': [models.Index(fields=['target', 'status', 'available_at'], name='srch_deliv_tgt_stat_avail_idx'), models.Index(fields=['status', 'lock_expires_at'], name='srch_deliv_stat_lease_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'target'), name='search_delivery_event_target_uq')],
            },
        ),
        migrations.CreateModel(
            name='SearchIndexBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mapping_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('created', '已创建'), ('backfilling', '回填中'), ('catching_up', '追平中'), ('ready', '已就绪'), ('serving', '服务中'), ('retired', '已退役'), ('failed', '失败')], default='created', max_length=16)),
                ('checkpoint_page_id', models.PositiveBigIntegerField(default=0)),
                ('scanned', models.PositiveBigIntegerField(default=0)),
                ('succeeded', models.PositiveBigIntegerField(default=0)),
                ('failed', models.PositiveBigIntegerField(default=0)),
                ('missing', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='search.contentsearchtarget')),
            ],
            options={
                'verbose_name': '搜索索引构建',
                'verbose_name_plural': '搜索索引构建',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='srch_build_stat_updated_idx')],
            },
        ),
    ]
