# Generated by Django 5.2.8 on 2026-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsearchoutbox',
            name='mongo_content_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contentsearchoutbox',
            name='searchable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ContentSearchScopeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_page_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('retry', '待重试'), ('succeeded', '已完成'), ('dead', '死信')], default='pending', max_length=16)),
                ('checkpoint_page_id', models.PositiveBigIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.TextField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '内容搜索范围任务',
                'verbose_name_plural': '内容搜索范围任务',
                'indexes': [models.Index(fields=['status', 'created_at'], name='srch_scope_stat_created_idx'), models.Index(fields=['root_page_id', 'status'], name='srch_scope_root_stat_idx')],
            },
        ),
    ]
