# Generated by Django 5.2.8 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_contentsearchoutbox_mongo_content_id_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contentsearchoutbox",
            index=models.Index(
                fields=["status", "available_at"],
                name="srch_outbox_stat_avail_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentsearchdelivery",
            index=models.Index(
                fields=["status", "available_at"],
                name="srch_deliv_stat_avail_idx",
            ),
        ),
    ]
