# Generated by Django 5.2.8 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_contentsearchdelivery_dispatch_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentsearchdelivery",
            name="lease_reclaims",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
