# Generated by Django 5.2.8 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_contentsearchdelivery_lease_reclaims"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchindexbuild",
            name="catch_up_clean_streak",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchindexbuild",
            name="last_batch_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchindexbuild",
            name="last_batch_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchindexbuild",
            name="last_checkpoint_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchindexbuild",
            name="last_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="searchindexbuild",
            name="last_error_message",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="searchindexbuild",
            name="scan_upper_bound_page_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchindexbuild",
            name="superseded",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
