# Generated by Django 5.2.8 on 2025-11-18 08:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfoliopage_options_alter_portfoliopage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('embed_block', 7), ('card', 10), ('featured_posts', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', '选择标题大小'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': '插入要嵌入的 URL。例如： https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['ai', 'bold', 'italic', 'link']}), 10: ('wagtail.blocks.StructBlock', [[('heading', 8), ('text', 9), ('image', 4)]], {'group': '选项'}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['ai', 'bold', 'italic', 'link'], 'required': False}), 12: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPage']}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('heading', 8), ('text', 11), ('posts', 13)]], {'group': '选项'})}, help_text='使用此部分列出您的项目和技能。'),
        ),
    ]
