# Generated by Django 5.1 on 2025-05-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagecomment',
            options={'verbose_name': '博客评论', 'verbose_name_plural': '博客评论'},
        ),
    ]
