# Generated by Django 5.1 on 2025-05-06 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_blogpagecomment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagecomment',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='blogpagecomment',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='blogpagecomment',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='blogpagecomment',
            name='author_website',
        ),
        migrations.RemoveField(
            model_name='blogpagecomment',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='blogpagecomment',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='blogpagecomment',
            name='can_edit_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='可编辑截止时间'),
        ),
        migrations.AddField(
            model_name='blogpagecomment',
            name='dislike_count',
            field=models.IntegerField(default=0, verbose_name='点踩数'),
        ),
        migrations.AddField(
            model_name='blogpagecomment',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='blogpagecomment',
            name='replied_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpagecomment',
            name='reply_count',
            field=models.IntegerField(default=0, verbose_name='回复数'),
        ),
        migrations.AlterField(
            model_name='blogpagecomment',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpagecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.blogpagecomment'),
        ),
        migrations.AlterField(
            model_name='blogpagecomment',
            name='status',
            field=models.CharField(choices=[('approved', '已批准'), ('deleted', '已删除')], default='approved', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reaction_type', models.SmallIntegerField(choices=[(1, '赞'), (-1, '踩')])),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comments.blogpagecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论反应',
                'verbose_name_plural': '评论反应',
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
