# Generated by Django 5.1 on 2025-05-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_blogpagecomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagecomment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='blogpagecomment',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='用户代理'),
        ),
        migrations.AlterField(
            model_name='blogpagecomment',
            name='status',
            field=models.CharField(choices=[('approved', '已批准'), ('deleted', '已删除'), ('pending', '待审核')], default='approved', max_length=20, verbose_name='状态'),
        ),
    ]
